#!/bin/sh

echo "----Starting app git deployment by calling ci/git/process-post-receive----"

./post-receive-script -w WEBDIRVALUE -g GITDIRVALUE -u ADMINUSERNAMEVALUE -p PHPEXECUTABLEVALUE -k COMPOSERCOMMANDVALUE -x WEBSERVERUSERVALUE -v WEBSERVERUSERGROUPVALUE

# add below modifiers to compile laravel js components as well
# --compile-js --remove-node-vendor
