#!/bin/sh

echo "----Starting app git deployment----"

WEBDIRECTORY=WEBDIRVALUE
GITDIRECTORY=GITDIRVALUE

echo "Pushing $COMMIT to repository."
echo "Suspending Application"
cd $WEBDIRECTORY
php artisan down

echo "Checking out latest"
cd $GITDIRECTORY
git --work-tree=$WEBDIRECTORY --git-dir=$GITDIRECTORY checkout -f

#GIT_WORK_TREE=$WEBDIRECTORY git fetch origin master;
#GIT_WORK_TREE=$WEBDIRECTORY git checkout -f;

cd $WEBDIRECTORY

#echo "Prep Packages"
#npm install

#echo "Running Mix tasks"
#npm install
#npm run prod


#echo "Updating composer (Optional)"
#composer self-update

echo "Running composer install"
composer install --optimize-autoloader --no-dev

#echo "Running outstanding migrations"
#php artisan migrate --force

echo "Clearing Cache"
php artisan cache:clear
php artisan config:cache

echo "Cache routes"
php artisan route:cache

echo "Caching views"
php artisan view:cache


echo "Bringing Application Online"
php artisan up

echo "Deployment finished!"
