#!/bin/bash

#HANDLE PARAMS
COMPILEJS=false
REMOVE_NODEVENDOR=false
PARAMS=""
DEBLOYROOT="/var/repo/debloy"
NOVACOMPONENTSFOLDER="nova-components"

while (( "$#" )); do
  case "$1" in
    -w|--web-directory)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        WEBDIRECTORY=$2
        shift 2
      else
        echo "Error: web directory argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    -g|--git-directory)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        GITDIRECTORY=$2
        shift 2
      else
        echo "Error: git directory argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    -u|--admin-username)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        ADMINUSERNAME=$2
        shift 2
      else
        echo "Error: admin username argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    -c|--compile-js)
      COMPILEJS=true
      shift
      ;;
    -r|--remove-node-vendor)
      REMOVE_NODEVENDOR=true
      shift
      ;;
    -h|--help)
      echo -e "\n\n\t\t----Process git post receive hook Help----\n"
      echo -e "\t-w, --web-directory \t  web folder\n\t-g, --git-directory \t  git folder\n\t-u, --admin-username \t  admin username"
      echo -e "\t-c, --compile-js \t  compile js components \n\t-r, --remove-node-vendor  remove node vendor directory after js compile\n\n"
      exit 0
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done

# set positional arguments in their proper place
eval set -- "$PARAMS"

if [[ -z $WEBDIRECTORY ]]; then
    echo "the web directory is required use -h flag for for help"
    exit 1
fi

if [[ -z $GITDIRECTORY ]]; then
    echo "the git directory is required use -h flag for for help"
    exit 1
fi

if [[ -z $ADMINUSERNAME ]]; then
    echo "the admin username is required use -h flag for for help"
    exit 1
fi

#echo "webdir is $WEBDIRECTORY"
#echo "gitdir is $GITDIRECTORY"
#echo "admin user is $ADMINUSERNAME"
#echo "compile js is $COMPILEJS"
#echo "remove node vendor is $REMOVE_NODEVENDOR"

# START DEPLOYMENT PROCESS
LARAVEL_APP_KEY_NOT_GENERATED_FILEPATH="${WEBDIRECTORY}/.appkey_notgenerated"

echo "----Starting app git deployment from process post receive script----"

echo "Pushing $COMMIT to repository."
echo "Suspending Application"
cd $WEBDIRECTORY
php artisan down

echo "Checking out latest"
cd $GITDIRECTORY
git --work-tree=$WEBDIRECTORY --git-dir=$GITDIRECTORY checkout -f

#GIT_WORK_TREE=$WEBDIRECTORY git fetch origin master;
#GIT_WORK_TREE=$WEBDIRECTORY git checkout -f;

cd $WEBDIRECTORY

echo "Npm Packages"
if [ "$COMPILEJS" = true ] ; then
  echo "Running Mix tasks"
  npm install
  npm run prod
fi

#Compile local Nova components
echo "Compiling Nova components"
NOVACOMPONENTSPATH="$WEBDIRECTORY/$NOVACOMPONENTSFOLDER"

if [[ -d $NOVACOMPONENTSPATH ]]; then
    echo "nova components directory ($NOVACOMPONENTSPATH) found, starting nova components compilation"

    #list of components to compile
    find "$NOVACOMPONENTSPATH" -maxdepth 1 -mindepth 1 -type d | while read dir; do
      #Compile each component
      echo "Compiling nova component located at $dir"
      cd "$dir"
      echo "running composer for current component ($NOVACOMPONENTSPATH)"
      composer install --no-dev
      composer update --no-dev
      echo "running npm for current component ($NOVACOMPONENTSPATH)"

      #remove node_modules if exists
      NODE_MODULES_PATH="$dir/node_modules"
      if [[ -d $NODE_MODULES_PATH ]]; then
        echo "node_modules directory ($NODE_MODULES_PATH) found, removing before npm install"
        rm -rf "$NODE_MODULES_PATH"
        echo "removing package-lock.json and yarn.lock if exists"
        rm "$NODE_MODULES_PATH"/package-lock.json
        rm "$NODE_MODULES_PATH"/yarn.lock
        echo "forcing npm cache clear"
        npm cache clear --force
      fi

      npm install
      npm run prod
    done
else
    echo "nova components directory ($NOVACOMPONENTSPATH) not found, skipping Nova components compilation"
fi

cd $WEBDIRECTORY

#echo "Updating composer (Optional)"
#composer self-update

echo "Running composer install"
composer install --optimize-autoloader --no-dev

#echo "Running outstanding migrations"
#php artisan migrate --force

echo "Clearing Cache"
php artisan cache:clear
php artisan config:cache

echo "Cache routes"
php artisan route:cache

echo "Caching views"
php artisan view:clear
php artisan view:cache

echo "Bringing Application Online"
php artisan up

echo "checking if first deployment"

if [[ -f "$LARAVEL_APP_KEY_NOT_GENERATED_FILEPATH" ]]; then
 #generate app key if not not yet generated
 echo "app key not yet generated, generating"
 php artisan key:generate

 rm -f $LARAVEL_APP_KEY_NOT_GENERATED_FILEPATH

 #link storage
 echo "linking storage also"
 php artisan storage:link
else
 echo "not first deployment, not generating key and linking storage"
fi

#set proper permissions on files
echo "setting proper permissions"
sudo $DEBLOYROOT/ci/set-webfolder-permissions "$WEBDIRECTORY" "$ADMINUSERNAME"

echo "Deployment finished!"

exit 0
